### PR TITLE
Logo iteration 1

### PR DESCRIPTION
**Pull request by Chronomyst**
Added 3 iteations of the design I had in mind. The colours are inspired by the logo provided and the background is hexadecimal code for BinEd.
The shape chosen is a hexagon and the lines in the middle outline the letters H and E, signifying Hexadecimal Editor.

### CODE REVIEW

**Comment by hajdam** [comment]
Well, it has a bit too fineprint and I don't see "E" letter in it.. I don't see how it could be reasonably used as an icon... I assume it's for android icon?
Preferably it would be great to follow standard specification: https://developer.android.com/google-play/resources/icon-design-specifications

For better idea here is how it would look next to other existing hexadecimal editors I tested on Android phone (maybe I should have include white background on first two images?):
https://bined.exbin.org/images/android-hexedit-screenshot-1.png

**Comment by Chronomyst** [comment]
My bad, I meant to specify that the first two are to be over a white
rectangle as their background yes
I do agree with your point about fine print.
I'll work on other designs and get back to you.

**Comment by hajdam** [comment]
Well, don't want to sound picky, but actually letters HE won't properly represent the tool as HexEditor is not typically shortened as HE. Also name of the project is BinEd as of "Binary Editor" so I would much more prefer something more numerical with zeros and ones - currently used logo on [homepage](https://bined.exbin.org) plays on this with "i" letter represented like as 1 with zero above for example.

From two logos I prefer logo5 as it seems hard for me to decrypt content of the logo4 even thou it looks much more techno-magical I would say ;-)

Maybe it could be extended to HEX something around this shape? https://bined.exbin.org/images/logo5-mod.png
Looks a bit fishy, I know :-(

I hope it's not insolent to ask for changes at this point, I'm grateful for all the work.

**Comment by Chronomyst** [comment]
It's more than okay to ask for changes. Client satisfaction is the key :)
I'll get to work with the feedback asap!!

**Comment by hajdam** [comment]
It looks good, but I think this also have same fine-print issue as first iteration.

Now, I'm a bit hesitant, maybe to suggest to replace "HEX" with 0/1, but that would also break the whole concept as 6-sides from "hexa" :-(

Or to keep HEX, but drop 0/1, although it would not fully match BinEd name of the project... :-(

Also could you try blue color? Looks like I don't know what I want... Such clients are so much pain, right? :-(

Anyway, gotta go sleep, but thank you for all the great work!

**Comment by hajdam** [comment]
I don't know, maybe blue is not a great idea... :-/
https://bined.exbin.org/images/logo6-mod.png

**Comment by hajdam** [comment]
Well, I guess I'm going to rely on your opinion here. Don't want to complicate things.
It seems logo6 would be ok anyway, so if you can provide vector variant, we can conclude this right away...
bined.exbin.org/images/android-hexedit-screenshot-2.png

**Comment by hajdam** [comment]
Hi again,
as you are not responding anymore, I assume you are either busy or don't intend to continue to work on this :-(
I assume I'll not use this as it's not a vector image.

Thank you for all your work and best regards.
Included on project website: https://bined.exbin.org/?icon-proposals

**Comment by Chronomyst** [comment]
Hey, I'm really sorry. I am actually in the hospital currently and have
been for the past couple of weeks.
Health just took a major hit.
I did not want to make it seem like I did not want to work on it but had
simply not been able to check my laptop or phone for any updates.

Again, I'm really sorry about no response on my end.

**Comment by Chronomyst** [comment]
If it's not too much trouble, I am due to be discharged in a week and would
love to work on the changes then as I'd have my laptop with me finally.

If not, I completely understand if you'd like to go forward with another
person.

**Comment by Chronomyst** [comment]
As for the 0/1 idea, we could go for something like this
Please excuse the low fidelity, I had to draw it on my phone

**Comment by hajdam** [comment]
Hi,
I'm sorry to hear that you are in hospital. In that case I understand you were not able to respond.
Please don't force yourself, there is no need to rush anything as there is plenty of time.
I also have some long-term health issues which delayed my work on this project strongly.

I wish you speedy recovery.

**Comment by Chronomyst** [comment]
Thank you so much for understanding. I can imagine how frustrating it can
be to not get a response.
I hope your health is faring better now and shall stay well in the future :)
I'll keep you updated on the work as soon as I get back home!

**Comment by hajdam** [comment]
Hi, I don't seem to see any image if you tried to insert one here (same goes for https://github.com/exbin/bined/issues/2 )...

**Comment by Chronomyst** [comment]
Oh I'm sorry I had attached the images but I'm guessing they didn't go
through.
https://imgur.com/a/QPOe9t0

**Pull request closed without merging**
